- hosts: prod
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: Add Google Chrome package base for Yum
      blockinfile:
        path: /etc/yum.repos.d/google-chrome.repo
        create: yes
        block: |
          [google-chrome]
          name=google-chrome
          baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
          enabled=1
          gpgcheck=1
          gpgkey=https://dl.google.com/linux/linux_signing_key.pub

    - name: Update package manager cache
      run_once: true
      yum:
        name: tar
        state: present
        update_cache: yes
      ignore_errors: yes

  tasks:
    - name: Install packages
      package:
        state: present
        name:
          - git
          - java-1.8.0-openjdk-devel
          - curl
          - google-chrome-stable

  roles:
    - role: gantsign.maven
    - role: lean_delivery.jmeter
    - role: cloudalchemy.node-exporter
    - role: cloudalchemy.prometheus
      prometheus_scrape_configs:
        - job_name: 'host'
          static_configs:
            - targets: ['localhost:9100']
              labels:
                env: prod
        - job_name: 'app'
          metrics_path: '/dbo/actuator/prometheus'
          static_configs:
            - targets: ['localhost:8080']
              labels:
                env: prod

  post_tasks:
    - name: Start JMeter remote agent
      shell: "nohup jmeter-server -Dserver.rmi.ssl.disable=true -Djava.rmi.server.hostname={{ ansible_host }} -Dserver.rmi.localport=42129 &"
      args:
        chdir: "{{ lookup('env','JMETER_HOME') }}"
